Repository GoTogether-Inc/frontend, pull requests merged in 2025-04, with the labels that each got.

#89 fix: 잘못된 형식의 코드 에러 해결
  src/features/dashboard/ui/Checklist.tsx
  yarn.lock
Labels: 🛠️ BugFix

#104 feat: 마이페이지 api 연동
  src/pages/menu/ui/MyPage.tsx
Labels: 🔧 Feature

#109 refact: ticket api 리팩토링
  src/features/ticket/api/ticket.ts
  src/features/ticket/hooks/useTicketHook.ts
  src/features/ticket/model/TicketContext.tsx
  src/features/ticket/model/ticketCreation.ts
  src/features/ticket/model/ticketInformation.ts
  src/pages/dashboard/ui/ticket/TicketCreatePage.tsx
  src/pages/dashboard/ui/ticket/TicketListPage.tsx
  src/widgets/dashboard/ui/TicketItem.tsx
  src/widgets/event/ui/TicketInfo.tsx
Labels: 🪄 Refactoring
